# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - oraclejdk14
# используем режим обычного пользователя для сборки проекта.
sudo: false
# JDBC
services:
  postgresql
# Изменяет текущую временную зону.
before_install:
  - export TZ=Europe/Moscow
  - date
  # JDBC создание базы данных
  - psql -c 'create database cinema;' -U postgres
# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - roman9628@gmail.com
    on_success: never # default: change
    on_failure: always # default: always